parameters:
#    pz_s_license_info.example.class: PzS\LicenseInfoBundle\Example

services:
#    pz_s_license_info.example:
#        class: %pz_s_license_info.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
